apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: regextester
  name: regextester
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: regextester
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: regextester
    spec:
      containers:
        - image: shellclear/nginx-regex-tester
          name: regextester
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
